version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: linux
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: npm run test
      - run:
          name: Upload coverage reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["13.9.0"]
